token:
  signer:
    id: RS256
    privateKey: "MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAolTwjZ1UCrIzW7wg
    VdGtYbAEdUJzA7E1JVlLfbBwAt3psGwO5MvUAOr4nyTp2W6kujtyNgKqZGONCTR6
    ViCJwwIDAQABAkA1cK8Mf9m197pOnd0rQ27HtRGSpMCGW6U6WW4vv5DwcCVeTHUQ
    w8zYux6B6kUa82D2ypmBKhJYPDyoMT4m1/x5AiEA1zZGx3jonUmVCEDFPx0oLSA0
    KOMCoOV5BCuX0VNArh8CIQDBGQEPl1pQL219QpxiBUE2NVqpkZul8Jr0E/gp28yn
    3QIgc3FfCFNYXD8DXbj41cE7MvGqaSBU4aAWiWElABlrgbsCIAnimM5Ohj4Sn31J
    Gq5d7H+07YY+wQQWtCgImayy5uA1AiEAxF0h+9nX7Y799xmoKnGfGrOszV2r37xo
    RBIBCe07D/w="